controller:
  serviceType: NodePort
  nodePort: 32000
  installPlugins:
    - kubernetes:4252.v6f6ec98e46fc
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.5.2
    - configuration-as-code:1850.va_a_8c31d3158b_
    - docker-workflow:580.vc0c340686b_54
    - github:1.40.0
    - pipeline-stage-view:2.34
    - blueocean:1.27.14
    - sonar:2.17.2
  
  persistence:
    enabled: true
    existingClaim: jenkins-pvc
    storageClass: ""
  
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins configured automatically by JCasC"

agent:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"